on:
  workflow_dispatch:

jobs:
  my_job:
    name: Package Language Pack
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Pyth
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - run: python my_script.py
      - name: Create timestamp
        id: create_timestamp
        run: echo "::set-output name=timestamp::$(date '+%y.%m.%d')"
        shell: bash 
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.create_timestamp.outputs.timestamp }}
          release_name: 汉化资源包-v
          draft: false
          prerelease: false
      - name: Update release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TLSAftermath-Language-Package-v${{ steps.create_timestamp.outputs.timestamp }}.zp
          asset_name: TLSAftermath-Language-Package-v${{ steps.create_timestamp.outputs.timestamp }}.zip
          asset_content_type: application/zip
