name: Package
on: workflow_dispatch

jobs:
  my_job:
    name: Package Language Pack
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with: 
          python-version: '3.11' 
      - run: python main.py
